Fix scaling of timeline images
element-hq/element-x-android pull request #1941
Opened 2023-12-01 12:05 UTC by jmartinesp

## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

The scaling behaviour now matches iOS:

- Fit content scaling, not Crop.
- Min/max height, not min/max aspect ratio. Changes the aspect ratio to take into account width, then height.

## Motivation and context

Fixes #1940.

## Screenshots / GIFs

In the PR.

## Tests

- Send an image with long height.
- Check how it looks in the timeline.

## Tested devices

- [x] Physical
- [ ] Emulator
- OS version(s): 11

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [x] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-x-android/blob/develop/CONTRIBUTING.md#changelog
- [x] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR

2023-12-01 12:42 UTC, ganfra commented
![Screenshot_20231201-133713.png](https://github.com/vector-im/element-x-android/assets/8754928/2792aa59-d9d8-4c2d-b381-5e0be8dcd506)

This doesnt work nicely for very large or very high images...

2023-12-01 12:43 UTC, jmartinesp commented
Could we test those in the iOS app, to compare what they look like? Maybe I messed up the implementation, or maybe that's just what their algorithm does.

2023-12-01 12:45 UTC, ganfra commented
> Could we test those in the iOS app, to compare what they look like? Maybe I messed up the implementation, or maybe that's just what their algorithm does.

Honestly I think we should keep cropping, thats what other messenger apps are doing. We could just have a bigger maxHeight maybe. @VolkerJunginger

2023-12-01 12:51 UTC, jmartinesp commented
This is what something similar looks like on iOS:

<details>
<summary>Details</summary>
<img src="https://github.com/vector-im/element-x-android/assets/480955/badc1de2-abca-4371-9697-382eb55e25bb" />
</details>

2023-12-02 03:36 UTC, seankhl commented
Just my two cents as a user: 

I think the WhatsApp and pre-PR solutions are worse, because they are misleading about the contents of the image. It's not clear that I wasn't just sent a black square, whereas at least with the element-x iOS and telegram solutions I can be like okay, there's more detail than I can easily see from the timeline image, let me download it or click and zoom.

The new element-x android solution is okay, but the background color being much larger than the image and the image not being centered in it feels unnecessary and is a bit visually awkward and distracting. In that sense maybe it could be made to conform more to the element-x iOS version.

The final note I'd like to make that the rounded corners of the messages would have a larger negative impact on these very narrow images if the background is not present, as shown in the iOS version. Maybe it would be good to make the background just wide or tall enough to capture the rounded corner, so the image can remain rectilinear while providing the least distracting background? Not sure the exact ideal solution to that, but the rounded corner cutting into the image and obscuring some of it is worth avoiding or at least considering in the design.

2023-12-02 14:18 UTC, jmartinesp commented
I was using Telegram desktop today and I saw another possible solution, something like they do here:

<img width="390" alt="image" src="https://github.com/vector-im/element-x-android/assets/480955/7091f9e2-e0ae-4108-a86f-7b97aecabb0f">


We could overlay the blurhash image and the actual: this way, the bubble still looks like a bubble and the actual image is displayed. I don't know how it'll look with tiny images though.

2023-12-03 08:45 UTC, seankhl commented
The blurhash as background looks good and I like how the rounded corners aren't impacting the image.

I also like how there is no timestamp overlapping with the image in the Telegram desktop version. I think this aspect is worth considering for Element, too. I see no reason why a design couldn't be made that avoids overlapping with the image while being as good as the current one in all other respects. Not trying to criticize, just pointing out that keeping the image completely unmodified and unobscured seems strictly better to me.

2023-12-11 08:41 UTC, jmartinesp commented
I was on holidays last week, I'm continuing with this work now. @VolkerJunginger , @amshakal what do you think about the issue found above and the possible solutions? To me, [the blurhash one](https://github.com/vector-im/element-x-android/pull/1941#issuecomment-1837159283) looks like the best option, and as a second option the telegram Android one where images with a width or height smaller than a min value don't actually show a preview (last spoiler tag [here](https://github.com/vector-im/element-x-android/pull/1941#issuecomment-1836069002).

In any case, doing any of these changes would mean doing the equivalent on iOS. I think the blurhash one should be fairly easy to do since all we'd had to do is not replace the loading blurhash background with the loaded image, but overlay them.

2023-12-14 17:06 UTC, ganfra approved these changes

2023-12-15 08:33 UTC, bmarty requested changes
Thanks for the update. There is an issue regarding the background color, else I think it's fine.
It's a shame that we do not have a preview with the image and the blurhash behind. Not a P1 to investigate this thought.

2023-12-15 08:33 UTC, bmarty commented on tests/uitests/src/test/snapshots/images/ui_S_t[f.messages.impl.timeline.components_TimelineItemEventRowForDirectRoom_null_TimelineItemEventRowForDirectRoom-Day-17_17_null,NEXUS_5,1.0,en].png
I think we need to have a background color, else the bubble does not render nicely...

2023-12-15 08:33 UTC, bmarty commented on tests/uitests/src/test/snapshots/images/ui_S_t[f.messages.impl.timeline.components_TimelineItemEventRowForDirectRoom_null_TimelineItemEventRowForDirectRoom-Night-17_18_null,NEXUS_5,1.0,en].png
... and this will also fix this issue.

2023-12-15 08:33 UTC, bmarty commented on features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/timeline/components/MessageEventBubble.kt
> +        !state.displayBackground -> Color.White
You should use background color of the bubble, see my remark on the screenshots.

2023-12-15 08:57 UTC, jmartinesp commented on tests/uitests/src/test/snapshots/images/ui_S_t[f.messages.impl.timeline.components_TimelineItemEventRowForDirectRoom_null_TimelineItemEventRowForDirectRoom-Day-17_17_null,NEXUS_5,1.0,en].png
This is what iOS looks like and what we've decided to use for now, given the deadline, since otherwise it would mean extra work for the iOS team, although this will probably be revisited soon. I took into account the suggestions to have a white background so images with transparency render nicely.

Maybe we could add a subtle border radius for these images so the bubble keeps its shape, something like this?

<details>
<summary>Screenshot</summary>
<img src='https://github.com/element-hq/element-x-android/assets/480955/05a2eb06-f284-4b61-b8b6-b4f0eef202ae' />
</details>

2023-12-15 09:28 UTC, bmarty commented on tests/uitests/src/test/snapshots/images/ui_S_t[f.messages.impl.timeline.components_TimelineItemEventRowForDirectRoom_null_TimelineItemEventRowForDirectRoom-Day-17_17_null,NEXUS_5,1.0,en].png
Can we have the bubble background color and white background for the image only (and maybe black background on dark theme)?
Like this this is not OK I think, but yes, definitely better with the bubble border.

2023-12-15 11:24 UTC, bmarty commented on tests/uitests/src/test/snapshots/images/ui_S_t[f.messages.impl.timeline.components_TimelineItemEventRowForDirectRoom_null_TimelineItemEventRowForDirectRoom-Day-17_17_null,NEXUS_5,1.0,en].png
With the bubble color I've got this:

|Light|Dark|
|-|-|
|<img width="355" alt="image" src="https://github.com/element-hq/element-x-android/assets/3940906/de6907ac-71a6-4367-adad-4bc4392ea985">|<img width="375" alt="image" src="https://github.com/element-hq/element-x-android/assets/3940906/9ca03141-1f25-4428-a2a4-a66488ae7a80">|

And I think it's fine.

We may want to improve the rendering of images with transparency in another PR, since applying a white background should be done to all images generated by users: room avatars, user avatars, images in timeline, etc.

@amshakal do you agree?

2023-12-15 12:24 UTC, amshakal commented on tests/uitests/src/test/snapshots/images/ui_S_t[f.messages.impl.timeline.components_TimelineItemEventRowForDirectRoom_null_TimelineItemEventRowForDirectRoom-Day-17_17_null,NEXUS_5,1.0,en].png
Yes, this makes sense to me. :)

2023-12-15 12:26 UTC, merged