WIP: plain text editor implementation
element-hq/element-x-android pull request #2840
Opened 2024-05-14 11:50 UTC by jmartinesp

## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Technical
- [ ] Other :

## Content

## Motivation and context

## Screenshots / GIFs

## Tests

- Step 1
- Step 2
- Step ...

## Tested devices

- [ ] Physical
- [ ] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR

2024-05-15 15:14 UTC, jmartinesp commented on features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/messagecomposer/MessageComposerPresenter.kt
> +        val richTextEditorState = richTextEditorStateFactory.create()
It's actually remembered, the name of this method is misleading. I'll see if we can change it or use some `rememberRIchTextEditorState()` helper function instead.

2024-05-15 15:20 UTC, jmartinesp commented on features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/messagecomposer/MessageComposerPresenter.kt
> +                // Give some time for the focus of the previous editor to be cleared
I forgot to remove this comment, nice catch!

2024-05-16 07:16 UTC, bmarty reviewed
Thanks, 2 small remarks after a static review, I will test it this morning.

2024-05-16 07:57 UTC, bmarty requested changes
Doing some test. The Markdown composer is working as expected, but when in `Rich`, the composer is not emptied when the message is sent, so user can sent the same message several times.

<img width="442" alt="image" src="https://github.com/element-hq/element-x-android/assets/3940906/fbcc4699-8887-4915-97f6-702dc6c7b11b">

2024-05-16 10:17 UTC, jmartinesp commented
@bmarty your issue above should be fixed in https://github.com/element-hq/element-x-android/pull/2840/commits/b73a63b95595f3db486c38111595c81bcd30b5a1.

I also added changes to your other comments.

2024-05-21 10:18 UTC, bmarty approved these changes
Thanks, working as expected now!

2024-05-21 10:21 UTC, jmartinesp commented
Nice! I'll release a RTE version compatible with these changes and merge the PR.

2024-05-21 11:58 UTC, merged

2024-05-21 11:59 UTC, jmartinesp commented
The Maestro job got stuck after finishing so it was in a limbo. I just force merged.